### ISSUE TITLE
Update container image location

### ISSUE THREAD

**Issue by andreasgerstmayr** [grafana/tempo-operator#204]
Currently the container gets published at `ghcr.io/os-observability/tempo-operator/tempo-operator`.

I'd suggest to publish it at `ghcr.io/os-observability/tempo-operator`, to conform with the traditional `<org>/<image>` scheme. Wdyt?

**Comment by frzifus** [comment]
sounds good :)

**Comment by rubenvp8510** [comment]
+1

**Comment by pavolloffay** [comment]
There is not much benefit for doing so. The `ghcr.io/os-observability/tempo-operator/tempo-operator` uses ghcr convention to link the image to the repository (though maybe the same could be done with seeting some metadata in the image.)

**Comment by andreasgerstmayr** [comment]
> There is not much benefit for doing so. The `ghcr.io/os-observability/tempo-operator/tempo-operator` uses ghcr convention to link the image to the repository (though maybe the same could be done with seeting some metadata in the image.)

Yep, the `docker/metadata-action@v4.3.0` action currently sets the metadata (`org.opencontainers.image.source`). In the GitHub docs I see references to `ghcr.io/NAMESPACE/IMAGE_NAME` [1,2,3], not to `ghcr.io/NAMESPACE/REPO/IMAGE_NAME`.
It's just a cosmetic change though.

[1] https://docs.github.com/en/packages/learn-github-packages/connecting-a-repository-to-a-package#connecting-a-repository-to-a-container-image-using-the-command-line
[2] https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#pushing-container-images
[3] https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
