### ISSUE TITLE
Expose custom operator metrics 

### ISSUE THREAD

**Issue by pavolloffay** [grafana/tempo-operator#308]
Ideas:

- {failing, versions} upgrades
- {failing} reconciliation loop
- {version} created instances

As a next step create alerting rules.

**Comment by andreasgerstmayr** [comment]
* reconciliation loop metrics are already included by kubebuilder (number, errors, time): https://book.kubebuilder.io/reference/metrics-reference.html
* Tempo versions can be queried with `tempo_build_info` or grouped by cluster `sum by (cluster) (tempo_build_info)`
* in #332 I added tempo operator version metrics and TempoStack status condition metrics.

I'll add upgrade metrics come once upgrades are implemented.
