### ISSUE TITLE
Reduce the number of structs that we use for the storages

### ISSUE THREAD

**Issue by iblancasa** [grafana/tempo-operator#314]
Would it make sense to consolidate all Azure storage params in a single struct?
* `manifestutils.AzureStorage`
* `manifests.AzureStorage`
* `config.azureStorage` (options.go)
* `config.AzureStorage` (configmap.go)

_Originally posted by @andreasgerstmayr in https://github.com/os-observability/tempo-operator/pull/283#discussion_r1136039390_

**Comment by andreasgerstmayr** [comment]
This will also resolve #409
