### ISSUE TITLE
Clarify featureflag for OCP route - Add gateway route/ingress support to CRD

### ISSUE THREAD

**Issue by pavolloffay** [grafana/tempo-operator#318]
At the moment the operator config defines 

```go
	// GatewayRoute enables creating an OpenShift Route for the TempoStack
	// gateway to expose the service to public internet access.
	// More details: https://docs.openshift.com/container-platform/latest/networking/understanding-networking.html
	GatewayRoute bool `json:"gatewayRoute,omitempty"`

	// OpenShiftRoute enables creating OpenShift Route objects.
	// More details: https://docs.openshift.com/container-platform/latest/networking/understanding-networking.html
	OpenShiftRoute bool `json:"openshiftRoute,omitempty"`
```

https://github.com/os-observability/tempo-operator/blob/bb15e421ca04f3361e84687f60afd9cf16e2358a/apis/config/v1alpha1/projectconfig_types.go#L61

Perhaps these two could be merged or  `OpenShiftRoute`  should have a better description for APIs/services it exposes.

cc) @andreasgerstmayr

**Comment by andreasgerstmayr** [comment]
You're right, the current docs for `OpenShiftRoute` should be updated. Something like `OpenShiftRoute specifies if the cluster supports OpenShift Route objects`?

**Comment by pavolloffay** [comment]
+1 on the approach for having s feature gate `openshiftRoute` that will tell the operator that route kind is available and then having a flag in CRD per component to create a route/ingress.

**Comment by pavolloffay** [comment]
done https://github.com/grafana/tempo-operator/blob/83a4b08d5f4f79dfc6522b418bb4f4d4f9e9ad4d/apis/config/v1alpha1/projectconfig_types.go#L65
