### ISSUE TITLE
[DOC] Tempo Operator doc 

### ISSUE THREAD

**Issue by knylander-grafana** [grafana/tempo-operator#407]
RE: Work on Tempo Operator and related documentation. Where should this content be stored?  

TIP: For help with documentation, refer to the [Writer's Tookit](https://grafana.com/docs/writers-toolkit/).

**Reference: Loki Operator** 
There is a Loki Operator that has docs on it's own site. The docs are in the Loki repository, but in a different folder from the rest of the project's documentation. 
* The Loki Operator docs are published on their own site:  https://loki-operator.dev/docs/ 
* The Loki Operator docs currently live in the Loki repository: https://github.com/grafana/loki/tree/main/operator/docs (which is a different directory than /docs/sources/, where the main docs live)
Note: @JStickler will be helping with the Loki Operator content and where it lives.

**Content location considerations**

If we have docs for a Tempo Operator, where should this doc be stored? 
* If the Tempo Operator doc will be published with the Tempo OSS docs on https://grafana.com/docs/tempo, then the Operator docs should be incorporated into the /tempo docs folder, https://github.com/grafana/tempo/tree/main/docs/sources/tempo.
* If the Tempo Operator docs will be published on another site, then the content can added to a folder (i.e., operator folder) in https://github.com/grafana/tempo/tree/main/docs/sources.

**Comment by pavolloffay** [comment]
@knylander-grafana would it be possible to have tempo-operator docs as a separate product listing in grafana docs? 
![Screenshot of Tempo documentation _ Grafana Tempo documentation](https://user-images.githubusercontent.com/5618424/237046200-a97ca7de-1b34-4e5e-af34-9890ca47b2b0.jpg)

**Comment by knylander-grafana** [comment]
@pavolloffay @joe-elliott We started discussing where the Tempo Operator docs should be stored. Is there a concern with resolving version differences if the Operator docs in the Tempo docs under Manage? 

@JStickler How are the Loki Operator docs handled? Will they be embedded in the Loki docs?

**Comment by pavolloffay** [comment]
> Is there a concern with resolving version differences if the Operator docs in the Tempo docs under Manage?

I am not quite sure what you mean. But right now the operator is versioned separately and there always will be a dedicated operator version for given tempo version.

**Comment by JStickler** [comment]
@knylander-grafana Since the Operator is just one installation option, I don't see the point of having it as a top level item in the navigation.  I have an open [issue](https://github.com/grafana/loki/issues/8812) to move the location of the files in the repo and publish the operator docs under the Setup heading with the other installation methods.

**Comment by knylander-grafana** [comment]
@JStickler Thank you. That sounds reasonable.

**Comment by knylander-grafana** [comment]
@pavolloffay Here's an overview of our proposed process for including the TO docs in Tempo: 

* [Jack or Kim] Update the folder structure for the docs in the tempo-operator repo to match Grafana's docs (i.e., use a docs/sources/<content> instead of just /docs/<content>) and start syncing files for every release to a directory in the Grafana website repository. [Tempo Operator Team] reviews PRs. 
* [Jack or Kim] Review markdown to verify compatibility with Hugo and custom short codes (initial quick review looks good)
* [Jack or Kim] Once the content is synced to the Grafana website repository, then we can mount the content in tempo/setup/tempo-operator. 

We will end up with directories for every version of tempo and tempo-operator docs. We'll have to manually maintain the mapping that says mount this version of tempo-operator docs into this version of tempo docs. This process will eventually be automated. 

We need to get our proposed process above approved before we can start.

**Comment by pavolloffay** [comment]
First PR https://github.com/grafana/tempo/pull/2596

**Comment by knylander-grafana** [comment]
First PR is merged. Content from first PR is here: 
* https://grafana.com/docs/tempo/next/setup/operator/
* https://grafana.com/docs/tempo/next/setup/

This content will be live with the next Tempo release.

**Comment by andreasgerstmayr** [comment]
I think we can close this issue, as the content is already live in the grafana docs?

**Comment by knylander-grafana** [comment]
Yes, I think we're good to close this issue.
