### ISSUE TITLE
Recover resource.requests for manager pod

### ISSUE THREAD

**Issue by iblancasa** [grafana/tempo-operator#426]
According to the the [OpenShift conventions guide](https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#resources-and-limits), we should recover the `resources.requests`  field for the Tempo operator.

> Therefore, cluster components SHOULD NOT be configured with resource limits.
>
> However, cluster components MUST declare resource requests for both CPU and memory.

**Comment by andreasgerstmayr** [comment]
Merged in #427
