### ISSUE TITLE
tempostack_status_condition should be reset when CR is deleted

### ISSUE THREAD

**Issue by andreasgerstmayr** [grafana/tempo-operator#451]
The `tempostack_status_condition` metric should get reset (all values=0) when its `TempoStack` CR gets deleted.

However, currently there is no way in the operator to be notified about the deletion. Not sure what's the best way - extending the defaulter or validator webhook to get notified about `DELETE` events? But this action (resetting metric values) it's neither defaulting or validating.

**Comment by pavolloffay** [comment]
can be closed with no action.
