### ISSUE TITLE
How to enable Metrics-generator ?

### ISSUE THREAD

**Issue by dampsoft-david** [grafana/tempo-operator#497]
Hi, 

we would like to enable the Metric-generator component to send us Span metrics to a mimir backend. 
Unfortunately I could not find a way to configure this with the help of the Tempo Operator documentation. 

Did I miss the possibility or is this not possible with the Tempo Operator so far?

Greetings
David

**Comment by pavolloffay** [comment]
hi @dampsoft-david this is currently not implemented in the operator. 

Internally we are planning to support this in the OpenTelemetry collector.

**Comment by dampsoft-david** [comment]
hi @pavolloffay thanks for the quick reply. 
So if I understand correctly there will be an OpenTelemetryCollector plugin in the future which will take over this functionality ?

**Comment by pavolloffay** [comment]
There is already:
* https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/spanmetricsconnector
* https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/servicegraphconnector

**Comment by dampsoft-david** [comment]
thanks for clarification, only searched for Tempo specific plugins.
But makes sense that it's a otel feature. 
So we will implement the connectors in our otel Collector for the metrics.
