### ISSUE TITLE
Setup: tempo-operator with AWS IRSA / IAM

### ISSUE THREAD

**Issue by faabsen** [grafana/tempo-operator#553]
Hello together,

according to the documentation of grafana/tempo it is possible to use [Amazon S3](https://grafana.com/docs/tempo/latest/configuration/s3/) with AWS IAM ([IRSA via WebIdentity](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)) or
AWS [EC2 instance role](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html). 

Unfortunately, the tempo-operator requires a secret (`spec.storage.secret`) for the TempoStack configuration. Is there a way to bypass this behaviour?

Cheers,
Fabian

**Comment by pavolloffay** [comment]
I don't think there is at the moment. It's something that can be added. 

cc) @iblancasa

**Comment by iblancasa** [comment]
It is not currently supported.
