### ISSUE TITLE
How to handle Config for tempo query frontend etc

### ISSUE THREAD

**Issue by diptripa** [grafana/tempo-operator#565]
I was looking through the documentation to find out how we can control the configuration.

When trying to query large number of traces I see this error and query frontend pod restarts:
level=warn ts=2023-08-22T19:34:28.661690386Z caller=grpc_logging.go:64 method=/frontend.Frontend/Process duration=1m53.096692989s err="rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (5322995 vs. 4194304)" msg=gRPC

Would also like to find how we can control the number of replicas through the controller.
Apologies if this details are readily available, but I couldnt find them.

Thanks

**Comment by pavolloffay** [comment]
Would increasing number of replicas of querier solve the issue? That is already exposed in https://github.com/grafana/tempo-operator/blob/754a9adb68bb8261f1c0eaac3ec8e9e6a8d8730d/apis/tempo/v1alpha1/tempostack_types.go#L441

**Comment by diptripa** [comment]
Not sure if it would because this is a single query for the frontend and the frontend crashes due to this error.

**Comment by andreasgerstmayr** [comment]
Sounds like we need to make
```
server:
    # Max gRPC message size that can be received
    # This value may need to be increased if you have large traces
    [grpc_server_max_recv_msg_size: <int> | default = 4194304]

    # Max gRPC message size that can be sent
    # This value may need to be increased if you have large traces
    [grpc_server_max_send_msg_size: <int> | default = 4194304]
```
configurable.

I wonder if we should create a new field in the CR for every single configuration option, or use some other approach? Some 'overlay config' which allows customizing/overwriting arbitrary fields in the configuration file?

**Comment by diptripa** [comment]
Yeah overlay config kind of a thing seems do able and should be pretty straightforward?

**Comment by andreasgerstmayr** [comment]
Completed in #718.
