### ISSUE TITLE
Upgrade Tempo to 2.2

### ISSUE THREAD

**Issue by josunect** [grafana/tempo-operator#594]
I realized that tempo operator last version uses Tempo 2.1. 

It would be possible to upgrade Tempo to, at least 2.2? So the [select](https://grafana.com/docs/tempo/latest/traceql/#selection) is available for the TraceQL queries, between [other improvements](https://github.com/grafana/tempo/releases/tag/v2.2.0).

**Comment by andreasgerstmayr** [comment]
Hi @josunect!

@pavolloffay updated Tempo to 2.2.1 in #554. This change will be included in the next release of the operator.

**Comment by josunect** [comment]
Thanks, @andreasgerstmayr !
