### ISSUE TITLE
Generated code should be created by the build

### ISSUE THREAD

**Issue by kevinearls** [grafana/tempo-operator#62]
There are several situations (some of which I will list below) where either building locally changes generated code which then has to be reverted before committing, or developers need to run generate targets manually, and then that code needs to be checked in.

In the first case, building an image on a developer's machine will change ```config/manager/kustomization.yaml``` and this change will need to be reverted before making a commit.

For the second, If this build is the same as the jaeger-operator or opentelemetry-collector-operator there are Makefile targets that such as ```api-docs``` that must be run manually before a commit and whatever files they change need to be added to the commit.

We should decide what is the best way to deal with generated code, and have this automated and done by the build where possible

**Comment by andreasgerstmayr** [comment]
A workaround would be to reset the changed files after deployment, for example:
```
$ IMG=docker.io/${USER}/tempo-operator:dev-$(date +%s) make generate bundle docker-build deploy && IMG=controller:latest make bundle
```

imho a better solution would be to make the `$(KUSTOMIZE) edit set image controller=` change in a temporary directory, which doesn't get checked in.
