### ISSUE TITLE
Reduce test times for e2e tests

### ISSUE THREAD

**Issue by kevinearls** [grafana/tempo-operator#98]
This is a follow up to #91   In that test I ran tracegen for 30 seconds to avoid a race condition in the verification step where traces may not yet be available.

If it's not possible to fix this via configuration then maybe add a retry loop to the verification step.

**Comment by pavolloffay** [comment]
The 30seconds: https://github.com/grafana/tempo-operator/blob/edec6e294884dd2d38a81d392e2c3112d81478fa/tests/e2e/smoketest-with-jaeger/02-generate-traces.yaml#L15

**Comment by pavolloffay** [comment]
+1 we can consider a shorter time or report a specific amount of data
