### ISSUE TITLE
Ingester fails on DigitalOcean Kubernetes due to permission issues

### ISSUE THREAD

**Issue by ThomasVitale** [grafana/tempo-operator#996]
Tempo 2.5.0 (supported in Tempo Operator 0.11.0+) switched user from `root` to `tempo` (`10001:10001`) and ownership of `/var/tempo`. In some Kubernetes distributions such as DigitalOcean, persistent volumes are always created with a filesystem owned by `root:root`, which means the Ingester Pod will fail with the following error.

```log
level=error ts=2024-07-30T08:55:08.620090627Z caller=main.go:121 msg="error running Tempo" err="failed to init module services: error initialising module: store: failed to create store: mkdir /var/tempo/wal: permission denied"
```

Unfortunately, DigitalOcean Kubernetes doesn't support the `mountOptions` settings to change the file permissions in the mounted volume, so Tempo Operator cannot be used in that environment as-is.

If I understand correctly, Tempo Operator 0.11.0 introduced a Job that runs when upgrading the Operator from previous versions to change the permissions on the volume (see https://github.com/grafana/tempo-operator/releases/tag/v0.11.0). Would it be an idea to allow running that same Job even on new installations, in environments like DigitalOcean Kubernetes? (perhaps, behind a configuration flag)

If that's not possible, I see two other options to make Tempo Operator support DigitalOcean Kubernetes:

- Allow the configuration of an "initContainer" for the Ingester component, responsible for changing the permissions explicitly (solution describe in the DigitalOcean [documentation](https://docs.digitalocean.com/products/kubernetes/how-to/add-volumes/#setting-permissions-on-volumes))
- Allow the configuration of the SecurityContext for the Ingester component to run the container as `1000:1000` instead of `10001:10001`, though not really a production-ready solution. This is what the tempo-distributed Helm chart does.

**Comment by pavolloffay** [comment]
Thanks for reporting this. 

Would setting the `securityContenxt.fsGroup`  help you to resolve the issue on digital ocean? See https://github.com/grafana/helm-charts/pull/3161#issuecomment-2197202507 


Perhaps the operator could always set it.

**Comment by ThomasVitale** [comment]
@pavolloffay thanks so much for the quick answer. I've just verified on a DigitalOcean cluster that by setting the following to the `StatetulSet` for the ingester component solves the problem.

```yaml
securityContenxt:
    fsGroup: 10001
```

It would be great if the Operator would allow that configuration. Even better if it's by default.

**Comment by siegenthalerroger** [comment]
I'm facing the same issue on AKS with the clean deployment of a TempoStack. Is there a workaround that works currently or is the only option a downgrade?

**Comment by pavolloffay** [comment]
You can switch is to `UnmanagedMode` and fix the permission manually https://github.com/grafana/tempo-operator/blob/main/apis/tempo/v1alpha1/tempostack_types.go#L35. 

The unmanaged mode allows you to directly modify k8s objects managed by the operator.

**Comment by Jeansen** [comment]
> [@pavolloffay](https://github.com/pavolloffay) thanks so much for the quick answer. I've just verified on a DigitalOcean cluster that by setting the following to the Pod spec in the `StatetulSet` for the ingester component solves the problem.
> 
> securityContenxt:
>   fsGroup: 10001
> It would be great if the Operator would allow that configuration. Even better if it's by default.

I think this should be a default. How should one know that a specific user or group has to be set? It's good this can be overwritten, but by definition that's the job of an operator since the operator instruments and utilizes tempo.

**Comment by heltonscampos** [comment]
I've resolved re-building grafana-tempo image seting root for user,  and upload on another Registry and set this new image for my deployment. 
Like this:  `FROM grafana/tempo:2.7.1

USER root

RUN mkdir -p /var/tempo/ && \
    chown -R 1000:1000 /var/tempo/

USER root:root


ENTRYPOINT ["/tempo"]`

**Comment by Dutchy-** [comment]
I encountered a permission denied today on a fresh install of tempo on AKS and I was able to set the securityContext fsGroup for the ingester using `template.ingester.podSecurityContext` in `TempoStack`. Without it, the ingester gave a permission denied on `/var/tempo/wal`.

Just adding this here for other people who find this through google.
